#!/bin/bash

echo "---- Script de Execucao do Sonar ------"

sleep 2

echo "----- Inicio Sonar -------"

sleep 2

cd /opt/sonarqube-5.6.3/bin/linux-x86-64/
./sonar.sh start

sleep 2

echo "----- Analise o Projeto ------  "

sleep 2

cd ~/Downloads/audopt-desenho/
#cd ~/Downloads/fis-jogos-master/trabalho_2

sonar-runner

sleep 2

echo "------ Exibindo Resultados -------"

sleep 2

cd /opt/sonar-scanner-2.8/bin/
python codigo_sonar.py
